# Generated by Django 4.0.6 on 2022-07-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table_is_free_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
