# Generated by Django 4.0.6 on 2022-07-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_remove_order_price_remove_order_table_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tables',
            field=models.ManyToManyField(blank=True, related_name='order', to='tables.table'),
        ),
    ]
