# Generated by Django 4.0.6 on 2022-07-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_order_tables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderTable',
        ),
    ]
